Repository rackerlabs/technical-blog, pull requests merged in 2020-12, with the labels that each got.

#348 key mgmt aws
  content/blog/2020/2020-12-01-key-management-and-hsms-for-aws-workloads/index.md
Labels: publish: delay, review: author

#344 Onica leveraging
  bioinfo.txt
  content/blog/2020/2020-12-01-leveraging-aws-to-prepare-your-ecommerce-platform-for-the-unexpected/index.md
Labels: review: editor

#365 substitutes PR 362, this's been edited, ready for r&m
  content/blog/2020/2020-12-07-from-datacenters-to-kubernetes-on-aws/index.md
Labels: review: peer

#377 migrates blog
  content/blog/2020/2020-12-11-the-value-of-joining-your-local-aws-meetup-group/index.md
Labels: review: peer

#379 Add Dependabot automated security update bot
  .github/dependabot.yml
Labels: security

#392 updates title
  content/blog/2020/2020-12-15-accelerate-your-business-with-iot/index.md
Labels: review: editor

#394 re post
  content/blog/2020/2020-12-17-maximize-your-salesforce-investment-with-managed-services/Picture1.png
  content/blog/2020/2020-12-17-maximize-your-salesforce-investment-with-managed-services/index.md
Labels: review: peer

#401 update and standardize process and procedures
  CONTRIBUTING.md
Labels: review: peer

#400 Add new blog: Getting the cloud right
  content/blog/2020/2020-12-17-getting-the-cloud-right-aws-well-architected-framework/index.md
Labels: review: editor

#409 add author image
  bioinfo.txt
  content/blog/2020/2020-12-18-aws-for-sap-migration-strategies/index.md
Labels: review: peer

#412 Add new blog: How to deploy Docker on AWS whitepaper
  content/blog/2020/2020-12-21-how-to-deploy-docker-on-aws-whitepaper/index.md
Labels: review: editor

#411 Add new blog: Companies are turning to AWS
  content/blog/2020/2020-12-21-why-companies-are-turning-to-aws-managed-services/index.md
Labels: review: editor

#413 Add new blog: When to use Elastic Beanstalk
  content/blog/2020/2020-12-22-when-to-use-elastic-beanstalk-custom-ami-versus-standard-ami/index.md
Labels: review: editor

#414 new tricore blog
  bioinfo.txt
  content/blog/2020/2020-12-23-restore-oracle-database-using-rman-duplicate-in-oracle-12c/index.md
Labels: review: author

#415 Add new blog: Deep dive on Amazon Aurora
  content/blog/2020/2020-12-28-deep-dive-on-amazon-aurora/index.md
Labels: review: editor

#418 Add blog: AWS benefits: Why should you consider migrating?
  content/blog/2020/2020-12-29-aws-benefits-why-should-you-consider-migrating/index.md
Labels: review: editor

#423 Add blog: Introduction to Amazon Textract
  content/blog/2021/2021-01-04-introduction-to-amazon-textract/index.md
Labels: review: editor

#422 Deletes author avatar, broken link, will ask author for pic
  content/blog/2020/2020-08-18-rackspace-technology-makes-network-security-a-reality/index.md
Labels: review: editor

#421 Changes capitalization in title, tiny cosmetic change
  content/blog/2020/2020-10-27-postgres-backups-and-how-to-restore-them-on-object-rocket/index.md
Labels: review: editor

#420 Changes capitalization of title
  content/blog/2020/2020-11-25-a-guide-to-customizing-the-customer-journey-with-amazon-personalize/index.md
Labels: review: editor
