Repository rackerlabs/technical-blog, pull requests merged in 2020-10, with the labels that each got.

#222 handshake
  content/blog/2020/2020-10-15-the-ssl-and-tls-handshake-process/Picture1.png
  content/blog/2020/2020-10-15-the-ssl-and-tls-handshake-process/index.md
Labels: review: author, review: peer

#183 Add Vale linting CI
  .github/styles/Rackspace/exchange.yml
  .github/styles/Vocab/Rackspace/accept.txt
  .github/styles/Vocab/Rackspace/reject.txt
  .github/workflows/main.yml
  .gitignore
  .vale.ini
Labels: review: code

#224 Elastic search aliases
  content/blog/2020/2020-10-18-elastic-search-aliases/picture1.jpg
  content/blog/2020/2020-10-18-elastic-search-aliases/picture2.png
  content/blog/2020/2020-10-18-elastic-search-aliases/picture3.png
  content/blog/2020/2020-10-18-elastic-search-aliases/picture4.png
  content/blog/2020/2020-10-18-elastic-search-aliases/picture5.png
  content/blog/2020/2020-10-18-elastic-search-aliases/picture6.png
  content/blog/2020/2020-10-18-elastic-search-aliases/picture7.png
  content/blog/2020/2020-10-18-elastic-search-aliases/picture8.png
  content/blog/2020/2020-10-18-elastic-search-aliases/picture9.png
  content/blog/2020/2020-10-18-elasticsearch-aliases/index.md
Labels: review: peer

#227 migrates blogpost
  content/blog/2020/2020-10-19-clustered-elasticsearch-indexing-shard-and-replica-best-practices/index.md
  content/blog/2020/2020-10-19-clustered-elasticsearch-indexing-shard-and-replica-best-practices/picture1.jpg
  content/blog/2020/2020-10-19-clustered-elasticsearch-indexing-shard-and-replica-best-practices/picture2.png
  content/blog/2020/2020-10-19-clustered-elasticsearch-indexing-shard-and-replica-best-practices/picture3.jpg
  content/blog/2020/2020-10-19-clustered-elasticsearch-indexing-shard-and-replica-best-practices/picture4.jpg
  content/blog/2020/2020-10-19-clustered-elasticsearch-indexing-shard-and-replica-best-practices/picture5.jpg
Labels: review: peer

#232 format
  content/blog/2013/2013-05-02-powerclient-rackspace-cloud-api-powershell-client/index.md
Labels: review: peer

#231 format
  content/blog/2013/2013-04-29-speed-up-with-redis/index.md
Labels: review: peer

#230 format fix
  content/blog/2013/2013-04-22-displaying-prepared-code-with-syntax-highlighting-on-android/index.md
Labels: review: peer

#236 Ccl part one
  content/blog/2020/2020-10-22-are-you-prepared-for-disaster-recovery-a-comparison-of-public-cloud-options/index.md
Labels: review: author

#239 fix title
  content/blog/2020/2020-10-22-rackspace-cloud-native-security-v0.3-part-one/index.md
Labels: review: peer

#237 Code injection
  bioinfo.txt
  bottom.txt
  content/blog/2020/2020-10-21-code-injection-in-mongodb/index.md
  content/blog/2020/2020-10-21-code-injection-in-mongodb/picture1.jpg
  nano
Labels: review: peer

#240 Blog salesforce implementing
  content/blog/2020/2020-10-22-implementing-and-improving-your-salesforce-system-with-paced/index.md
Labels: review: peer

#243 minor changes in style
  content/blog/2020/2020-10-23-configure-elasticsearch-to-use-s3-for-snapshots/index.md
  content/blog/2020/2020-10-23-configure-elasticsearch-to-use-s3-for-snapshots/picture1.jpg
Labels: review: peer

#245 changes several style elements
  bioinfo.txt
  content/blog/2020/2020-10-26-what-is-polyglot-persistence/index.md
  content/blog/2020/2020-10-26-what-is-polyglot-persistence/picture1.png
  content/blog/2020/2020-10-26-what-is-polyglot-persistence/picture2.jpg
Labels: review: peer

#246 remove author avatar meta
  content/blog/2020/2020-10-26-what-is-polyglot-persistence/index.md
Labels: publish: ready

#252 rgc vmware
  content/blog/2020/2020-10-29-announcing-rackspace-government-cloud-expansion-and-partnership-with-vmware-and-dell/index.md
Labels: review: author

#259 Ccl fix titlr
  content/blog/2020/2020-10-22-rackspace-cloud-native-security/Picture1.png
  content/blog/2020/2020-10-22-rackspace-cloud-native-security/Picture2.png
  content/blog/2020/2020-10-22-rackspace-cloud-native-security/index.md
Labels: review: peer

#257 salesforce-integrations-buy-vs-build
  content/blog/2020/2020-10-29-salesforce-integrations-buy-vs-build/index.md
Labels: review: peer
