Repository rackerlabs/technical-blog, pull requests merged in 2020-11, with the labels that each got.

#262 six-steps-to-salesforce-adoption
  content/blog/2020/2020-11-02-six-steps-to-salesforce-adoption/index.md
  content/blog/2020/2020-11-02-six-steps-to-salesforce-adoption/salesforce-six-steps.png
Labels: review: peer

#268 fix title
  content/blog/2020/2020-10-21-introducing-metrics-dashboards-on-objectrocket/index.md
Labels: review: peer

#265 blog-optimize-salesforce
  content/blog/2020/2020-11-05-optimize-the-value-of-your-salesforce-investment/appexchange.png
  content/blog/2020/2020-11-05-optimize-the-value-of-your-salesforce-investment/dreamforce.jpg
  content/blog/2020/2020-11-05-optimize-the-value-of-your-salesforce-investment/index.md
  content/blog/2020/2020-11-05-optimize-the-value-of-your-salesforce-investment/training.png
  content/blog/2020/2020-11-05-optimize-the-value-of-your-salesforce-investment/value.jpg
Labels: review: peer

#272 blog crm
  content/blog/2020/2020-11-04-make-the-most-of-your-crm/index.md
Labels: review: peer

#281 fixes author's pic
  bioinfo.txt
  content/blog/2020/2020-11-10-using-logstash-to-load-csv-data-into-elasticsearch/index.md
Labels: review: peer

#287 fixes logstash
  content/blog/2020/2020-11-06-using-logstash-to-load-csv-data-into-elasticsearch/index.md
  content/blog/2020/2020-11-10-using-logstash-to-load-csv-data-into-elasticsearch/index.md
Labels: review: peer

#292 fix slug
  content/blog/2020/2020-11-11-optimizing-cloud-costs-with-spend-segmentation-and-chargeback/index.md
Labels: review: peer

#293 fix slug
  content/blog/2020/2020-11-09-objectrocket-has-single-sign-on-and-role-based-access-control/index.md
Labels: review: peer

#306 Redshift
  content/blog/2020/2020-11-17-amazon-redshift-best-practices-for-optimizing-query-performance/Column_SortKeys_Fig3_new.jpg
  content/blog/2020/2020-11-17-amazon-redshift-best-practices-for-optimizing-query-performance/Redshift_Architecture_Fig1.jpg
  content/blog/2020/2020-11-17-amazon-redshift-best-practices-for-optimizing-query-performance/index.md
Labels: review: editor

#337 fix meta
  content/blog/2020/2020-11-26-simplifying-data-lakes-with-aws-lake-formation/index.md
Labels: review: peer

#339 OCI types
  content/blog/2020/2020-11-25-different-types-of-oci-servers-in-the-cloud/Picture1.png
  content/blog/2020/2020-11-25-different-types-of-oci-servers-in-the-cloud/Picture2.png
  content/blog/2020/2020-11-25-different-types-of-oci-servers-in-the-cloud/Picture3.png
  content/blog/2020/2020-11-25-different-types-of-oci-servers-in-the-cloud/Picture4.png
  content/blog/2020/2020-11-25-different-types-of-oci-servers-in-the-cloud/Picture5a.png
  content/blog/2020/2020-11-25-different-types-of-oci-servers-in-the-cloud/Picture5b.png
  content/blog/2020/2020-11-25-different-types-of-oci-servers-in-the-cloud/Picture5c.png
  content/blog/2020/2020-11-25-different-types-of-oci-servers-in-the-cloud/Picture5d.png
  content/blog/2020/2020-11-25-different-types-of-oci-servers-in-the-cloud/Picture6.png
  content/blog/2020/2020-11-25-different-types-of-oci-servers-in-the-cloud/Picture7.png
  content/blog/2020/2020-11-25-different-types-of-oci-servers-in-the-cloud/Picture8.png
  content/blog/2020/2020-11-25-different-types-of-oci-servers-in-the-cloud/index.md
Labels: review: author, review: peer
